### ISSUE TITLE
Ensure Python app can handle SIGTERM/SIGKILL

### ISSUE THREAD

**Issue by halajohn** [TEN-framework/ten_framework.bak#115]
Go app had special handling for these signals.

**Comment by sunxilin** [comment]
The current status is that TEN Python app can handle SIGTERM/SIGKILL as the TEN signal handler is registered after the library 'libten_runtime' is loaded.  The performance is that 'ctrl+C' will trigger the TEN app gracefully close.

**Comment by halajohn** [comment]
The signal handler registered in `ten_runtime`'s `on_load` will not be overwritten in the Python environment. Therefore, in a Python TEN app, pressing Ctrl-C once will stop the app, and pressing Ctrl-C twice will forcibly exit the TEN app. Both behaviors are effective.
