### ISSUE TITLE
Enhance copyright notice for clarity and compliance

### ISSUE THREAD

**Issue by jserv** [TEN-framework/ten_framework.bak#13]
Each source file in this repository currently starts with the following notice:
```
// This file is part of the TEN Framework project.
// See https://github.com/TEN-framework/ten_framework/LICENSE for license
// information.
```

While this provides basic information, it deviates from common open-source practices by omitting the copyright owner's name and the year. To improve clarity and align with standard conventions, I suggest updating the notice to:
```
// Copyright (c) 2024 Agora
// This is free software; you can redistribute it and/or modify it under the
// terms of the Apache license, Version 2.0. A copy of the license can be found in the file
// "LICENSE" at the root of this distribution.
```

This enhancement will make the copyright notice more verbose and relevant, ensuring it meets typical open-source licensing standards.

Example projects:
* [mimalloc](https://github.com/microsoft/mimalloc)
* [airflow](https://github.com/apache/airflow)

**Comment by halajohn** [comment]
Hi, I have modified the file header to include the description of the copyright owner and added some license information. If there are any issues with the content of the license, I can address them here or create a dedicated discussion to document it.

**Comment by jserv** [comment]
Close via #21
