### ISSUE TITLE
In 1-app mode, if "app": "localhost" is present graph definition, ten runtime should also prevent the graph from starting and log an error

### ISSUE THREAD

**Issue by halajohn** [TEN-framework/ten_framework.bak#176]

**Comment by leoadonia** [comment]
与 graph check 命令行一致.

10-21 15:03:58.036 89503(89503) W ten_app_start_predefined_graph@predefined_graph.c:158 [msgpack://127.0.0.1:8001/] The predefined graph is invalid, nodes[1]: 'localhost' is not allowed in graph definition, change the content of 'app' field to be consistent with '_ten::uri'

目前 predefined graph 有问题，只是 warning 日志. 待 message conversion 支持后, 改成错误退出. #160
