### ISSUE TITLE
[FEAT] We should load/build extensions when needed

### ISSUE THREAD

**Issue by plutoless** [TEN-framework/ten_framework.bak#260]
### Description

Currently, regardless of specifying extensions in property.json graph or not, ten will build and load all extensions under ten_packages/extensions folder. As we are having more than 20 extensions now, it's causing performance issues and make the development unnecessary long

### Environment

linux

### Steps to reproduce

any development

### Expected behavior

build and load when run should be fast.
only extensions relevant to graph should be build and loaded

### Actual behavior

regardless of specifying extensions in property.json graph or not, ten will build and load all extensions under ten_packages/extensions folder

### Version

0.4.0

### Severity

Critical

**Comment by plutoless** [comment]
Runtime Requirements and Setup

The runtime should be able to:

Determine Build Inclusion: Decide whether to include specific components in the build based on the manifest.
Decide on Loading: Use the graph to decide if a component should be loaded.
To implement this, we can start by setting up an environment initialization step. For instance, running:

```
make build --agent=example/westwoold
```

This command will:

Create symbolic links (ln) for manifest.json and property.json from example/westwoold to the agents directory.
Set these linked files as the default configurations for the build.
This approach enables selective and flexible builds, allowing the system to dynamically include or exclude agents as specified in their manifest files.

**Comment by wangyoucao577** [comment]
Only **install requirements(building time) and load(run time) for given python extensions** are the top priority for this issue. c++/go extensions aren't criticial here.

**Comment by halajohn** [comment]
It is now possible to load C++ and Python extensions based on the dependencies specified in the App's `manifest.json`. 

For the Go ecosystem, the Go app's build scripts need to be modified. The next step is to update the Go app's build scripts to determine which Go extensions to compile based on the dependencies listed in the App's `manifest.json`.

**Comment by halajohn** [comment]
Through [https://github.com/TEN-framework/ten_framework/pull/343](https://github.com/TEN-framework/ten_framework/pull/343), the functionality of loading extensions in Go based on the `dependencies` specified in the app's `manifest.json` has also been completed.

**Comment by halajohn** [comment]
In version 0.7.0, addons will be dynamically loaded solely because they are used in the graph being utilized. They will not be loaded simply because they exist in the file system (under `ten_packages/`) or are listed in `manifest.json`.
