### ISSUE TITLE
[BUG] graph check should not report error if dest property is not defined

### ISSUE THREAD

**Issue by plutoless** [TEN-framework/ten_framework.bak#265]
### Description

graph check should not report error if dest property is not defined

### Environment

linux

### Steps to reproduce

use 0.4.0 to run any graph

### Expected behavior

graph check should not report error if dest property is not defined

### Actual behavior

it's reporting issues

### Version

0.4.0

### Severity

Critical

**Comment by halajohn** [comment]
After internal discussion, there doesn't seem to be anything else that needs to be done for this issue.
