### ISSUE TITLE
[BUG] extension_tester_t still missed send_audio_frame/send_video_frame

### ISSUE THREAD

**Issue by wangyoucao577** [TEN-framework/ten_framework.bak#321]
### Description

https://github.com/TEN-framework/ten_framework/blob/main/core/include/ten_runtime/binding/cpp/internal/test/env_tester.h

The `extension_tester_t` will be used in extension testing, which requires `send_audio_frame/send_video_frame` but doesn't exist. 

### Environment

linux

### Steps to reproduce

1. expect the use `send_audio_frame/send_video_frame` in extension testing, but the apis don't exist.

### Expected behavior

`send_audio_frame/send_video_frame` exist.

### Actual behavior

`send_audio_frame/send_video_frame` don't exist.

### Version

0.4.2

### Severity

Critical

**Comment by wangyoucao577** [comment]
By the way, the `extension_tester_t` is part of API, which doesn't supposed in the `internal` folder.

**Comment by sunxilin** [comment]
send_audio/video_frame apis are provided in main branch now.

**Comment by halajohn** [comment]
The two PRs below should resolve this issue.

- [https://github.com/TEN-framework/ten_framework/pull/296](https://github.com/TEN-framework/ten_framework/pull/296)
- [https://github.com/TEN-framework/ten_framework/pull/338](https://github.com/TEN-framework/ten_framework/pull/338)

C++ test-related header files are also included in the unified `ten.h` for developers to use. The `internal/` directory represents header files that are referenced internally by `ten.h` and are not meant for internal use in the typical sense. However, to avoid confusion, the `internal/` folder name has been changed to `detail/` in the above PRs to better align with C++ naming conventions.
