### ISSUE TITLE
Set thread name for extension groups

### ISSUE THREAD

**Issue by wangyoucao577** [TEN-framework/ten_framework.bak#327]
Expect to see the names by `top` or in coredump file, which will helpful to investigate issues.

**Comment by halajohn** [comment]
Done. https://github.com/TEN-framework/ten_framework/tree/327-set-thread-name-for-extension-groups

Currently, the debugger allows viewing the extension group name. However, the Linux kernel enforces a maximum thread name length of 15 characters.

![image](https://github.com/user-attachments/assets/1e799f18-7be0-4709-9798-830dcc4a3e96)
