### ISSUE TITLE
Expect to compatible with python versions >=3.10

### ISSUE THREAD

**Issue by wangyoucao577** [TEN-framework/ten_framework.bak#83]
Currently only `python 3.10` is supported since both `ten_runtime_python` and `py_init_extension_cpp` links `libpython3.10.so` during building. Expect to support latest python versions for better compatibilites, i.e., `>=3.10`.

**Comment by halajohn** [comment]
Currently, the TEN framework does not hardcode a specific Python version to link against. Instead, it uses the `pkg-config` of the Python version installed in the build environment to determine the Python libraries to link. Therefore, as long as the Python version installed in the build environment is a newer version, the requirements of this issue can theoretically be fulfilled.

**Comment by wangyoucao577** [comment]
https://github.com/TEN-framework/ten_framework/blob/e06d69e24d1dc90b5a627e909f94783dadeb430c/core/src/ten_runtime/binding/python/native/BUILD.gn#L12 

Yes, switching to other Python versions, such as 3.12, is now straightforward with this configuration. However, it still requires re-linking both `libpython_addon_loader.so` and `libten_runtime_python.so`, which can be cumbersome for users. A better solution would be to publish separate versions of `python_addon_loader` and `ten_runtime_python` for each supported Python version, allowing users to choose the appropriate version for their needs.
